id: example_id
info:
  name: Example YAML Structure
  tags:
    - Tasty
    - Helpful
    - Cool
  author: example@mail.test
  descrption: This should be a value for testing. It can show the basic structure of the Yaml data as a test.
  reference:
    - https://example.example/index.html
    - https://no.security.example/index.html