id: test_id
info:
  name: Test YAML Structure
  tags: 
    - TestTAG
    - TestNoTAG
  author: example@mail.test
  descrption: This should be a value for testing. It can show the basic structure of the Yaml data as a test.
  reference:
    - https://example.example/index.html
    - https://lol.at.lol/index.html