name: Rust CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: wami
        path: target/debug/wami

  release:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Release
      run: cargo build --release --verbose
    - name: Modify README
      run: |
        sed -i "s|<binary_placehoder>|$(ls target/release/wami)|g" README.md
      working-directory: ${{ github.workspace }}
