name: Rust CI

on: 
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: wami
        path: target/debug/wami

  release:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Release
      run: cargo build --release --verbose
    - name: Modify README
      run: |
        cat README.md | grep binary &&
        placeholder=$(realpath target/release/wami) &&
        sed -i "s|<binary_placeholder>|$placeholder|g" README.md &&
        cat README.md | grep $placeholder &&
        mkdir bin
        cp $placeholder bin/
      env:
        ACCESS_TOKEN: ${{ secrets.rust.ci_readme_update }}

    - name: Commit and push changes
      run: |
        git status
        git config --global user.email "tb@evait.de"
        git config --global user.name "NxtTAB"
        git add bin/wami
        echo "git add bin/wami"
        git commit -m "add binary wami"
        git status
        git push
