name: Rust CI and Release

on: 
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Release_linux_x64
      run: cargo build --release --verbose
    
    - name: Copy release to destination
      run: cp ./target/release/wami ./assets/bin/linux_x64/wami
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1.0
        release_name: Release v0.1.0
        body: This is the new release
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create.release.outputs.upload_url }}
        asset_path: ./assets/bin/linux_x64/wami
        asset_name: wami
        asset_content_type: application/octet-stream
