name: Rust CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: my-program
        path: target/debug/wami

  release:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download binary
      uses: actions/download-artifact@v2
      with:
        name: wami
    - name: Release
      run: cargo build --release --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: wami
        path: target/releade/wami
